### ISSUE TITLE
Relationship between SPI and PDSI

### ISSUE THREAD

**Issue by jinshijian** [PNNL-TES/bahn-rs-test#11]
I analyzed the relationship between SPI and PDSI, there is no relationship between them. That makes sense, right? Because whether a year is wet or dry depend on only precipitation in this year (identified by SPI), rather than whether this site is in a drought site or not (identified by PDSI). 

![image](https://user-images.githubusercontent.com/13302161/56696763-cb2a2d80-66ba-11e9-9712-5553efc91b3e.png)

**Comment by bpbond** [comment]
Good! Yes, agreed, that does make sense. It's a really good "sanity check" though. Thanks!
